// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataLayer.Views;

public partial class TZ_21_07_2025Context : TZ_21_07_2025Context_Main
{
    public TZ_21_07_2025Context(DbContextOptions<TZ_21_07_2025Context> options)
        : base(options)
    {
    }

    public virtual DbSet<show_count_products_in_books_and_tool> show_count_products_in_books_and_tools { get; set; }

    public virtual DbSet<show_count_products_in_category> show_count_products_in_categories { get; set; }

    public virtual DbSet<show_number_of_users_order> show_number_of_users_orders { get; set; }

    public virtual DbSet<show_top_3_product> show_top_3_products { get; set; }

    public virtual DbSet<show_top_3_users_by_number_of_order> show_top_3_users_by_number_of_orders { get; set; }

    public virtual DbSet<show_users_without_password> show_users_without_passwords { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<show_count_products_in_books_and_tool>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("show_count_products_in_books_and_tools");

            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<show_count_products_in_category>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("show_count_products_in_category");

            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<show_number_of_users_order>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("show_number_of_users_orders");

            entity.Property(e => e.login)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<show_top_3_product>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("show_top_3_products");

            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<show_top_3_users_by_number_of_order>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("show_top_3_users_by_number_of_orders");

            entity.Property(e => e.login)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<show_users_without_password>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("show_users_without_password");

            entity.Property(e => e.id).ValueGeneratedOnAdd();
            entity.Property(e => e.login)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.mail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.password).HasMaxLength(100);
            entity.Property(e => e.patronymic).HasMaxLength(100);
            entity.Property(e => e.phone_number).HasMaxLength(20);
            entity.Property(e => e.registration_date).HasColumnType("datetime");
            entity.Property(e => e.surname).HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}