// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class category
{
    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public virtual ICollection<product> products { get; set; } = new List<product>();
}