// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class order
{
    public int id { get; set; }

    public int user_id { get; set; }

    public DateTime? order_placement_date { get; set; }

    public decimal total_amount { get; set; }

    public int status_id { get; set; }

    public string address { get; set; }

    public virtual ICollection<order_history> order_histories { get; set; } = new List<order_history>();

    public virtual ICollection<order_product> order_products { get; set; } = new List<order_product>();

    public virtual status_order status { get; set; }

    public virtual user user { get; set; }
}