// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class product
{
    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public decimal price { get; set; }

    public DateTime? date_added { get; set; }

    public virtual ICollection<order_product> order_products { get; set; } = new List<order_product>();

    public virtual ICollection<warehouse_product> warehouse_products { get; set; } = new List<warehouse_product>();

    public virtual ICollection<category> categories { get; set; } = new List<category>();
}