// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class status_order
{
    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public virtual ICollection<order_history> order_historynew_statusNavigations { get; set; } = new List<order_history>();

    public virtual ICollection<order_history> order_historyold_statusNavigations { get; set; } = new List<order_history>();

    public virtual ICollection<order> orders { get; set; } = new List<order>();
}