// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataLayer.Models;

public partial class TZ_21_07_2025Context : DbContext
{
    public TZ_21_07_2025Context(DbContextOptions<TZ_21_07_2025Context> options)
        : base(options)
    {
    }

    public virtual DbSet<category> categories { get; set; }

    public virtual DbSet<order> orders { get; set; }

    public virtual DbSet<order_history> order_histories { get; set; }

    public virtual DbSet<order_product> order_products { get; set; }

    public virtual DbSet<product> products { get; set; }

    public virtual DbSet<status_order> status_orders { get; set; }

    public virtual DbSet<user> users { get; set; }

    public virtual DbSet<users2> users2s { get; set; }

    public virtual DbSet<warehouse> warehouses { get; set; }

    public virtual DbSet<warehouse_product> warehouse_products { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<category>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__categori__3213E83FF7182FEE");

            entity.HasIndex(e => e.name, "UQ__categori__72E12F1B829E1094").IsUnique();

            entity.Property(e => e.description)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<order>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__orders__3213E83FB6A06BD2");

            entity.Property(e => e.address).HasMaxLength(500);
            entity.Property(e => e.order_placement_date)
                .HasDefaultValueSql("(dateadd(hour,(3),getutcdate()))")
                .HasColumnType("datetime");
            entity.Property(e => e.total_amount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.status).WithMany(p => p.orders)
                .HasForeignKey(d => d.status_id)
                .HasConstraintName("FK__orders__status_i__3D690CCA");

            entity.HasOne(d => d.user).WithMany(p => p.orders)
                .HasForeignKey(d => d.user_id)
                .HasConstraintName("FK__orders__user_id__3C74E891");
        });

        modelBuilder.Entity<order_history>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__order_hi__3213E83F04EF0D6C");

            entity.ToTable("order_history");

            entity.Property(e => e.comment).HasMaxLength(1000);
            entity.Property(e => e.date_of_change)
                .HasDefaultValueSql("(dateadd(hour,(3),getutcdate()))")
                .HasColumnType("datetime");

            entity.HasOne(d => d.new_statusNavigation).WithMany(p => p.order_historynew_statusNavigations)
                .HasForeignKey(d => d.new_status)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order_his__new_s__48DABF76");

            entity.HasOne(d => d.old_statusNavigation).WithMany(p => p.order_historyold_statusNavigations)
                .HasForeignKey(d => d.old_status)
                .HasConstraintName("FK__order_his__old_s__47E69B3D");

            entity.HasOne(d => d.order).WithMany(p => p.order_histories)
                .HasForeignKey(d => d.order_id)
                .HasConstraintName("FK__order_his__order__46F27704");
        });

        modelBuilder.Entity<order_product>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__order_pr__3213E83F66775142");

            entity.Property(e => e.price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.order).WithMany(p => p.order_products)
                .HasForeignKey(d => d.order_id)
                .HasConstraintName("FK__order_pro__order__422DC1E7");

            entity.HasOne(d => d.product).WithMany(p => p.order_products)
                .HasForeignKey(d => d.product_id)
                .HasConstraintName("FK__order_pro__produ__4321E620");
        });

        modelBuilder.Entity<product>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__products__3213E83FF0FD7089");

            entity.Property(e => e.date_added)
                .HasDefaultValueSql("(dateadd(hour,(3),getutcdate()))")
                .HasColumnType("datetime");
            entity.Property(e => e.description)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.price).HasColumnType("decimal(18, 2)");

            entity.HasMany(d => d.categories).WithMany(p => p.products)
                .UsingEntity<Dictionary<string, object>>(
                    "product_category",
                    r => r.HasOne<category>().WithMany()
                        .HasForeignKey("category_id")
                        .HasConstraintName("FK__product_c__categ__34D3C6C9"),
                    l => l.HasOne<product>().WithMany()
                        .HasForeignKey("product_id")
                        .HasConstraintName("FK__product_c__produ__33DFA290"),
                    j =>
                    {
                        j.HasKey("product_id", "category_id").HasName("PK__product___1A56936E50C212BF");
                        j.ToTable("product_categories");
                    });
        });

        modelBuilder.Entity<status_order>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__status_o__3213E83FC59AD23F");

            entity.HasIndex(e => e.name, "UQ__status_o__72E12F1BA180229B").IsUnique();

            entity.Property(e => e.description)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<user>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__users__3213E83FD6E9AF91");

            entity.HasIndex(e => e.login, "UQ__users__7838F272E38191DF").IsUnique();

            entity.HasIndex(e => e.mail, "UQ__users__7A21290455012AF6").IsUnique();

            entity.Property(e => e.login)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.mail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.password).HasMaxLength(100);
            entity.Property(e => e.patronymic).HasMaxLength(100);
            entity.Property(e => e.phone_number).HasMaxLength(20);
            entity.Property(e => e.registration_date)
                .HasDefaultValueSql("(dateadd(hour,(3),getutcdate()))")
                .HasColumnType("datetime");
            entity.Property(e => e.surname).HasMaxLength(100);
        });

        modelBuilder.Entity<users2>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__users2__3213E83F44CA9C69");

            entity.ToTable("users2");

            entity.HasIndex(e => e.login, "UQ__users2__7838F272046E888D").IsUnique();

            entity.HasIndex(e => e.mail, "UQ__users2__7A212904476AC349").IsUnique();

            entity.Property(e => e.login)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.mail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.patronymic).HasMaxLength(100);
            entity.Property(e => e.phone_number).HasMaxLength(20);
            entity.Property(e => e.registration_date)
                .HasDefaultValueSql("(dateadd(hour,(3),getutcdate()))")
                .HasColumnType("datetime");
            entity.Property(e => e.surname).HasMaxLength(100);
        });

        modelBuilder.Entity<warehouse>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__warehous__3213E83F3A511591");

            entity.Property(e => e.address).HasMaxLength(500);
            entity.Property(e => e.description)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<warehouse_product>(entity =>
        {
            entity.HasKey(e => new { e.product_id, e.warehouse_id }).HasName("PK__warehous__A036839E07400DA3");

            entity.HasOne(d => d.product).WithMany(p => p.warehouse_products)
                .HasForeignKey(d => d.product_id)
                .HasConstraintName("FK__warehouse__produ__2D32A501");

            entity.HasOne(d => d.warehouse).WithMany(p => p.warehouse_products)
                .HasForeignKey(d => d.warehouse_id)
                .HasConstraintName("FK__warehouse__wareh__2E26C93A");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}