// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class users2
{
    public int id { get; set; }

    public string login { get; set; }

    public string name { get; set; }

    public string surname { get; set; }

    public string patronymic { get; set; }

    public string mail { get; set; }

    public string phone_number { get; set; }

    public DateTime? registration_date { get; set; }
}